In [1]:
import pandas as pd
import numpy as np

In [3]:
# loc= 'C:\\Users\\Ramshankar\\OneDrive - iLink Systems Inc\\Documents\\Costco\\Dataset'

data_Inline = pd.read_excel('C:\\Users\\Ramshankar\\OneDrive - iLink Systems Inc\\Documents\\Costco\\Dataset\\Inventory Visibility - Dataset Updated.xlsx', sheet_name= 'Inline On-Hand')

In [4]:
data_Inline.head()

,CALENDAR_YR_NUM,CALENDAR_MO_NUM,COMPANY_CODE,BI_RPT_STATE_CODE,BI_RPT_REGION_DESC,BI_RPT_DISTRICT_DESC,LOCATION_LONG_NAME,MAJOR_DEPT_GRP_LONG_DESC,BI_DEPARTMENT_NUM_LDESC,BI_MAJOR_CATEGORY_CODE_DESC,...,BI_ITEM_CATEGORY_CODE_DESC,ITEM_DESC_1,OnHand_QTY,OnHand_AMT,OnOrder_QTY,OnOrder_AMT,InTransit_QTY,InTransit_AMT,Non-Saleable-Items_QTY,Non-Saleable-Items_AMT
0,2021,4,US,SC,SOUTHEAST,SE4,MT PLEASANT,FOOD,13 FOOD,T BREAD,...,TAD SPECIALTY BREAD,IRISH SODA BREAD 2.5 LBS,10,59.90,0,0.00,0,0.00,0,0.0
1,2021,11,US,KS,MID WEST,MW5,OVERLAND PARK,OTHER BUS.,94 OPTICAL,F FRAMES,...,FSR FRAME SUN RXABLE,VIA SPIGA VS424S (I),18,1079.82,8,479.92,4,239.96,0,0.0
2,2022,4,US,MI,MID WEST,MW1,BLOOMFIELD,FRESH FOOD,65 PRODUCE,1 PRODUCE,...,1K1 SALAD KITS ORGANIC,ORGANIC CAESAR SALAD KIT,7031,63208.69,3672,33011.28,648,5825.52,0,0.0
3,2021,3,US,HI,LA REGION,LA4,KAPOLEI,SOFTLINES,32 HOUSEWARES,J DINNERWARE,...,JAB CASUAL 20PC OR LESS SETS,GIBSON MONTEREY 16PC BLUE,284,11357.16,0,0.00,0,0.00,0,0.0
4,2021,12,US,IA,MID WEST,MW4,WEST DES MOINES,SOFTLINES,35 JEWELRY,D COLORED GEMS,...,DSB SEMI PREC PENDANTS OR NECKLACE,NJ597-1-98 14KYG RD 10MM,34,13599.66,16,6399.84,2,799.98,0,0.0

In [5]:
data_Inline['Data_type']= 'Inline'

In [6]:
data_Inline.head()

,CALENDAR_YR_NUM,CALENDAR_MO_NUM,COMPANY_CODE,BI_RPT_STATE_CODE,BI_RPT_REGION_DESC,BI_RPT_DISTRICT_DESC,LOCATION_LONG_NAME,MAJOR_DEPT_GRP_LONG_DESC,BI_DEPARTMENT_NUM_LDESC,BI_MAJOR_CATEGORY_CODE_DESC,...,ITEM_DESC_1,OnHand_QTY,OnHand_AMT,OnOrder_QTY,OnOrder_AMT,InTransit_QTY,InTransit_AMT,Non-Saleable-Items_QTY,Non-Saleable-Items_AMT,Data_type
0,2021,4,US,SC,SOUTHEAST,SE4,MT PLEASANT,FOOD,13 FOOD,T BREAD,...,IRISH SODA BREAD 2.5 LBS,10,59.90,0,0.00,0,0.00,0,0.0,Inline
1,2021,11,US,KS,MID WEST,MW5,OVERLAND PARK,OTHER BUS.,94 OPTICAL,F FRAMES,...,VIA SPIGA VS424S (I),18,1079.82,8,479.92,4,239.96,0,0.0,Inline
2,2022,4,US,MI,MID WEST,MW1,BLOOMFIELD,FRESH FOOD,65 PRODUCE,1 PRODUCE,...,ORGANIC CAESAR SALAD KIT,7031,63208.69,3672,33011.28,648,5825.52,0,0.0,Inline
3,2021,3,US,HI,LA REGION,LA4,KAPOLEI,SOFTLINES,32 HOUSEWARES,J DINNERWARE,...,GIBSON MONTEREY 16PC BLUE,284,11357.16,0,0.00,0,0.00,0,0.0,Inline
4,2021,12,US,IA,MID WEST,MW4,WEST DES MOINES,SOFTLINES,35 JEWELRY,D COLORED GEMS,...,NJ597-1-98 14KYG RD 10MM,34,13599.66,16,6399.84,2,799.98,0,0.0,Inline

In [7]:
data_Inline['CALENDAR_YR_NUM'].unique()

array([2021, 2022], dtype=int64)

In [8]:
data_Inline['CALENDAR_MO_NUM'].unique()

array([ 4, 11,  3, 12,  7,  6,  1,  9,  8,  2, 10,  5], dtype=int64)

In [9]:
data_Inline['COMPANY_CODE'].unique()       #We can drop "CN" from location

array(['US', 'CN'], dtype=object)

In [10]:
data_Inline['BI_RPT_STATE_CODE'].nunique()      #There are only 50 states in US but here it is 57

57

In [11]:
data_Inline['BI_RPT_REGION_DESC'].nunique() #In powerBI We have used 10 regions only

12

In [12]:
data_Inline['BI_RPT_REGION_DESC'].unique()

array(['SOUTHEAST', 'MID WEST', 'LA REGION', 'NORTHEAST',
       'CANADIAN BCTR/DLVRY', 'NORTHWEST', 'SD REGION', 'WESTERN CANADA',
       'TEXAS REGION', 'EASTERN CANADA', 'BAY AREA', 'BUSINESS CENTERS'],
      dtype=object)

In [13]:
data_Inline['BI_RPT_DISTRICT_DESC'].nunique() #44 Unique districs

44

In [14]:
data_Inline.columns

Index(['CALENDAR_YR_NUM', 'CALENDAR_MO_NUM', 'COMPANY_CODE',
       'BI_RPT_STATE_CODE', 'BI_RPT_REGION_DESC', 'BI_RPT_DISTRICT_DESC',
       'LOCATION_LONG_NAME', 'MAJOR_DEPT_GRP_LONG_DESC',
       'BI_DEPARTMENT_NUM_LDESC', 'BI_MAJOR_CATEGORY_CODE_DESC',
       'BI_GROUP_CATEGORY_CODE_DESC', 'BI_ITEM_CATEGORY_CODE_DESC',
       'ITEM_DESC_1', 'OnHand_QTY', 'OnHand_AMT', 'OnOrder_QTY', 'OnOrder_AMT',
       'InTransit_QTY', 'InTransit_AMT', 'Non-Saleable-Items_QTY',
       'Non-Saleable-Items_AMT', 'Data_type'],
      dtype='object')

In [15]:
data_Inline['LOCATION_LONG_NAME'].nunique()   # Location Name      675 in powerbi

668

In [16]:
data_Inline['MAJOR_DEPT_GRP_LONG_DESC'].nunique()    #4 ware in PowerBI "Major Department"

6

In [17]:
data_Inline['MAJOR_DEPT_GRP_LONG_DESC'].unique()    # 'OTHER BUS.' and 'NOT APPLICABLE MAJOR DEPARTMENT GROUP LONG DESCRIPTION' not there

array(['FOOD', 'OTHER BUS.', 'FRESH FOOD', 'SOFTLINES', 'HARDLINES',
       'NOT APPLICABLE MAJOR DEPARTMENT GROUP LONG DESCRIPTION'],
      dtype=object)

In [18]:
data_Inline['BI_DEPARTMENT_NUM_LDESC'].unique()     # "Department"

array(['13 FOOD', '94 OPTICAL', '65 PRODUCE', '32 HOUSEWARES',
       '35 JEWELRY', '19 DELI', '12 CANDY', '31 WOMENS APPAREL',
       '14 SUNDRIES', '24 MAJOR APPLIANCES', '16 LIQUOR',
       '39 MENS APPAREL', '21 OFFICE SUPPLIES', '26 SPORTING GOODS',
       '87 TIRE BALANCE FEE', '93 PHARMACY (OTC)', '22 TIRES',
       '34 DOMESTICS', '80 MISCELLANEOUS', '83 COUPONS', '36 MEDIA',
       '33 SMALL APPLIANCES', '11 TOBACCO', '20 HEALTH & BEAUTY AIDS',
       '23 HARDWARE', '96 HEARING AIDS', '18 FROZEN FOOD',
       '25 AUTOMOTIVE', '17 COOLER', '27 GARDEN', '38 HOME FURNISHINGS',
       '44 SPECIAL EVENTS', '95 MEMBERSHIP', '28 TOYS/SEASONAL',
       '70 1HR PHOTO LAB', '75 NON-FOODS TICKETS',
       '45 SPECIAL ORDER KIOSK', '29 STAMPS', '53 GASOLINE',
       '48 SUPPLIES'], dtype=object)

In [19]:
len(data_Inline['BI_DEPARTMENT_NUM_LDESC'].unique())

40

In [20]:
data_Inline['BI_MAJOR_CATEGORY_CODE_DESC'].nunique()   # "Major Category"

524

In [21]:
data_Inline['BI_GROUP_CATEGORY_CODE_DESC'].nunique()   #Not Used in PowerBI

1383

In [22]:
data_Inline['BI_ITEM_CATEGORY_CODE_DESC'].nunique()   #Not Used in PowerBI

2545

In [23]:
data_Inline['ITEM_DESC_1'].nunique()      # "Item"

7996

__Loading Online OH__

In [24]:
# loc= 'C:\\Users\\Ramshankar\\OneDrive - iLink Systems Inc\\Documents\\Costco\\Dataset'

data_Online = pd.read_excel('C:\\Users\\Ramshankar\\OneDrive - iLink Systems Inc\\Documents\\Costco\\Dataset\\Inventory Visibility - Dataset Updated.xlsx', sheet_name= 'Online On-Hand')

In [25]:
data_Online.head()

,CALENDAR_YR_NUM,CALENDAR_MO_NUM,COMPANY_CODE,BI_RPT_STATE_CODE,BI_RPT_REGION_DESC,BI_RPT_DISTRICT_DESC,LOCATION_LONG_NAME,MAJOR_DEPT_GRP_LONG_DESC,BI_DEPARTMENT_NUM_LDESC,BI_MAJOR_CATEGORY_CODE_DESC,...,BI_ITEM_CATEGORY_CODE_DESC,ITEM_DESC_1,OnHand_QTY,OnHand_AMT,OnOrder_QTY,OnOrder_AMT,InTransit_QTY,InTransit_AMT,Non-Saleable-Items_QTY,Non-Saleable-Items_AMT
0,2021,6,US,OH,BUSINESS DELIV-OTHER,DEPOT,DDC ECOM COLUMBUS OH,HARDLINES,24 MAJOR APPLIANCES,A TVS,...,AGA 65 IN ULTRA PREMIUM TVS,"LG OLEDCX 65OLEDCXAUA 65""",3534,6587664.66,350,647496.5,0,0.0,42,78099.58
1,2022,10,US,FL,BUSINESS DELIV-OTHER,DEPOT,DDC ECOM OCALA FL,SOFTLINES,38 HOME FURNISHINGS,J UPHOLSTERY,...,JBA LEATHER SOFAS,MITCH LEATHER SOFA,1167,2100588.33,0,0.0,0,0.0,0,0.00
2,2022,10,US,CA,BUSINESS DELIV-OTHER,DEPOT,MDO ECOM W SACRAMENTO CA,HARDLINES,24 MAJOR APPLIANCES,H MAJOR APPLIANCES,...,HAE FRENCH 4 DOOR DRAWER,LG 22CFT CD 4D FRNCH DR,3,9299.97,0,0.0,0,0.0,0,0.00
3,2021,2,US,GA,BUSINESS DELIV-OTHER,DEPOT,DDC ECOM ATLANTA GA,SOFTLINES,38 HOME FURNISHINGS,T ELECTRIC FIREPLACES,...,TUN FIREPLACE CONSOLE,"GABLES 74"" FIREPLACE CNSL",8,5599.92,0,0.0,0,0.0,0,0.00
4,2022,6,US,IL,BUSINESS DELIV-OTHER,DEPOT,MDO ECOM ITASCA IL,SOFTLINES,38 HOME FURNISHINGS,M GENERAL HOME DISPLAY AND HALL,...,MAF HALL CHESTS CONSOLES AND BOMBE,"CONRAD 55"" CONSOLE BLUE",2,1159.98,0,0.0,0,0.0,0,0.00

In [26]:
data_Online['Data_type']= 'Online'

In [27]:
data_Online['CALENDAR_YR_NUM'].unique()

array([2021, 2022], dtype=int64)

In [28]:
data_Online['CALENDAR_MO_NUM'].unique()

array([ 6, 10,  2,  9,  8,  3,  7, 11,  1,  4,  5, 12], dtype=int64)

In [29]:
data_Online['COMPANY_CODE'].unique()       #We can drop "CN" from location

array(['US', 'CN'], dtype=object)

In [30]:
data_Online['BI_RPT_STATE_CODE'].nunique()      #57 in Inline-OH and 23 in Online-OH

23

In [31]:
data_Online['BI_RPT_REGION_DESC'].nunique() #10 regions in Inline-OH and 5 in Online-OH

5

In [32]:
data_Online['BI_RPT_REGION_DESC'].unique()         #Only two are in Inline-OH

array(['BUSINESS DELIV-OTHER', 'WESTERN CANADA', 'OTHER BUSINESS CN',
       'SD REGION', 'NORTHWEST'], dtype=object)

In [33]:
data_Online['BI_RPT_DISTRICT_DESC'].nunique() #44 Unique districs in Online and 1 in online

1

In [34]:
data_Online['BI_RPT_DISTRICT_DESC'].unique()    #Depot only b

array(['DEPOT'], dtype=object)

In [35]:
#Checking weather 'Depot' is present in inline-OH

#data_Inline['BI_RPT_DISTRICT_DESC'].unique()

In [36]:
data_Online.columns

Index(['CALENDAR_YR_NUM', 'CALENDAR_MO_NUM', 'COMPANY_CODE',
       'BI_RPT_STATE_CODE', 'BI_RPT_REGION_DESC', 'BI_RPT_DISTRICT_DESC',
       'LOCATION_LONG_NAME', 'MAJOR_DEPT_GRP_LONG_DESC',
       'BI_DEPARTMENT_NUM_LDESC', 'BI_MAJOR_CATEGORY_CODE_DESC',
       'BI_GROUP_CATEGORY_CODE_DESC', 'BI_ITEM_CATEGORY_CODE_DESC',
       'ITEM_DESC_1', 'OnHand_QTY', 'OnHand_AMT', 'OnOrder_QTY', 'OnOrder_AMT',
       'InTransit_QTY', 'InTransit_AMT', 'Non-Saleable-Items_QTY',
       'Non-Saleable-Items_AMT', 'Data_type'],
      dtype='object')

In [37]:
data_Online['LOCATION_LONG_NAME'].nunique()   # Location Name      675 in powerbi & 668 in Inline and 48 in online

48

In [38]:
data_Online['LOCATION_LONG_NAME'].unique()

array(['DDC ECOM COLUMBUS OH', 'DDC ECOM OCALA FL',
       'MDO ECOM W SACRAMENTO CA', 'DDC ECOM ATLANTA GA',
       'MDO ECOM ITASCA IL', 'MDO ECOM BENICIA CA',
       'BOISBRIAND OPTICAL DIST', 'MDO ECOM KENT II WA',
       'MDO ECOM COLUMBIA MD', 'AIRDRIE ECOMMERCE', 'MDO ECOM NEWARK NJ',
       'MDO ECOM TAMPA FL', 'DDC ECOM MORRIS IL', 'LANGLEY ECOMMERCE',
       'MORRIS ECOMMERCE', 'FREDERICK ECOMMERCE', 'VARENNES ECOMMERCE',
       'MDO ECOM JANESVILLE WI', 'DDC ECOM DUPONT WA',
       'MDO ECOM SYOSSET NY', 'DDC ECOM GOULDSBORO PA', 'KATY ECOMMERCE',
       'DDC ECOM RIO PIEDRAS PR', 'NATIONAL CITY OPT DISTR',
       'MDO ECOM SYLMAR CA', 'MIRA LOMA ECOMMERCE',
       'DDC ECOM STOCKTON CA', 'SUMNER ECOMMERCE', 'MDO ECOM HOUSTON TX',
       'TRACY ECOMMERCE', 'MDO ECOM JACKSONVILLE FL',
       'MDO ECOM PORTLAND OR', 'MIRA LOMA ANNEX ECOMMERCE',
       'PEARL CITY MDO ECM', 'DDC ECOM ONTARIO CA', 'ATLANTA ECOMMERCE',
       'DDC ECOM GARLAND TX', 'MDO ECOM GRAPEVINE TX',
       'VAUGHAN ECOMMERCE', 'DDC ECOM AURORA CO', 'DDC ECOM MEMPHIS TN',
       'ECOMMERCE CWT MX', 'MDO ECOM PHOENIX AZ', 'MDO ECOM CERRITOS CA',
       'MONROE TOWNSHIP ECOMMERCE', 'MDO ECOM PFLUGERVILLE TX',
       'MDO ECOM SUNRISE FL', 'DDC ECOM ANCHORAGE AK'], dtype=object)

In [39]:
data_Online['MAJOR_DEPT_GRP_LONG_DESC'].nunique()    #4 ware in PowerBI "Major Department"

5

In [40]:
data_Online['MAJOR_DEPT_GRP_LONG_DESC'].unique()    # 'OTHER BUS.' and 'NOT APPLICABLE MAJOR DEPARTMENT GROUP LONG DESCRIPTION' not there
                                                    #only 3 present "Fresh Food" is not present

array(['HARDLINES', 'SOFTLINES', 'OTHER BUS.', 'FOOD',
       'NOT APPLICABLE MAJOR DEPARTMENT GROUP LONG DESCRIPTION'],
      dtype=object)

In [41]:
data_Online['BI_DEPARTMENT_NUM_LDESC'].unique()     # "Department"

array(['24 MAJOR APPLIANCES', '38 HOME FURNISHINGS', '94 OPTICAL',
       '34 DOMESTICS', '13 FOOD', '39 MENS APPAREL', '23 HARDWARE',
       '26 SPORTING GOODS', '29 STAMPS', '27 GARDEN',
       '20 HEALTH & BEAUTY AIDS', '32 HOUSEWARES', '33 SMALL APPLIANCES',
       '28 TOYS/SEASONAL', '93 PHARMACY (OTC)', '31 WOMENS APPAREL',
       '14 SUNDRIES', '12 CANDY', '25 AUTOMOTIVE', '80 MISCELLANEOUS',
       '96 HEARING AIDS', '21 OFFICE SUPPLIES', '75 NON-FOODS TICKETS',
       '35 JEWELRY', '36 MEDIA', '44 SPECIAL EVENTS', '22 TIRES'],
      dtype=object)

In [42]:
len(data_Online['BI_DEPARTMENT_NUM_LDESC'].unique())    #  Departement: 40 in Inline and 27 in Online

27

In [43]:
data_Online['BI_MAJOR_CATEGORY_CODE_DESC'].nunique()   # "Major Category": 524 in Inline and 338 in online

338

In [44]:
data_Online['BI_GROUP_CATEGORY_CODE_DESC'].nunique()   #Not Used in PowerBI: 1383 in Inline  and 847 online

847

In [45]:
data_Online['BI_ITEM_CATEGORY_CODE_DESC'].nunique()   #Not Used in PowerBI: 2545 in Inline and  1524 online

1524

In [46]:
data_Online['ITEM_DESC_1'].nunique()      # "Item" 7996 in Online and 5305

5305

### Appending Inline and online Data

In [47]:
data_combine= data_Inline.append(data_Online, ignore_index=True)

C:\Users\Ramshankar\AppData\Local\Temp\ipykernel_12104\446111615.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data_combine= data_Inline.append(data_Online, ignore_index=True)

In [48]:
data_combine.head()

,CALENDAR_YR_NUM,CALENDAR_MO_NUM,COMPANY_CODE,BI_RPT_STATE_CODE,BI_RPT_REGION_DESC,BI_RPT_DISTRICT_DESC,LOCATION_LONG_NAME,MAJOR_DEPT_GRP_LONG_DESC,BI_DEPARTMENT_NUM_LDESC,BI_MAJOR_CATEGORY_CODE_DESC,...,ITEM_DESC_1,OnHand_QTY,OnHand_AMT,OnOrder_QTY,OnOrder_AMT,InTransit_QTY,InTransit_AMT,Non-Saleable-Items_QTY,Non-Saleable-Items_AMT,Data_type
0,2021,4,US,SC,SOUTHEAST,SE4,MT PLEASANT,FOOD,13 FOOD,T BREAD,...,IRISH SODA BREAD 2.5 LBS,10,59.90,0,0.00,0,0.00,0,0.0,Inline
1,2021,11,US,KS,MID WEST,MW5,OVERLAND PARK,OTHER BUS.,94 OPTICAL,F FRAMES,...,VIA SPIGA VS424S (I),18,1079.82,8,479.92,4,239.96,0,0.0,Inline
2,2022,4,US,MI,MID WEST,MW1,BLOOMFIELD,FRESH FOOD,65 PRODUCE,1 PRODUCE,...,ORGANIC CAESAR SALAD KIT,7031,63208.69,3672,33011.28,648,5825.52,0,0.0,Inline
3,2021,3,US,HI,LA REGION,LA4,KAPOLEI,SOFTLINES,32 HOUSEWARES,J DINNERWARE,...,GIBSON MONTEREY 16PC BLUE,284,11357.16,0,0.00,0,0.00,0,0.0,Inline
4,2021,12,US,IA,MID WEST,MW4,WEST DES MOINES,SOFTLINES,35 JEWELRY,D COLORED GEMS,...,NJ597-1-98 14KYG RD 10MM,34,13599.66,16,6399.84,2,799.98,0,0.0,Inline

In [147]:
data_combine.shape

(20000, 23)

In [49]:
#data_combine.to_excel('Output\\OnIn_combine.xlsx', index=False)

In [50]:
len(data_combine.columns)

22

In [51]:
data_combine['year_month'] = pd.to_datetime(data_combine['CALENDAR_YR_NUM'].astype(str) + " - " + data_combine['CALENDAR_MO_NUM'].astype(str))
data_combine['year_month'] = data_combine['year_month'].dt.to_period('M')

In [52]:
data_combine

,CALENDAR_YR_NUM,CALENDAR_MO_NUM,COMPANY_CODE,BI_RPT_STATE_CODE,BI_RPT_REGION_DESC,BI_RPT_DISTRICT_DESC,LOCATION_LONG_NAME,MAJOR_DEPT_GRP_LONG_DESC,BI_DEPARTMENT_NUM_LDESC,BI_MAJOR_CATEGORY_CODE_DESC,...,OnHand_QTY,OnHand_AMT,OnOrder_QTY,OnOrder_AMT,InTransit_QTY,InTransit_AMT,Non-Saleable-Items_QTY,Non-Saleable-Items_AMT,Data_type,year_month
0,2021,4,US,SC,SOUTHEAST,SE4,MT PLEASANT,FOOD,13 FOOD,T BREAD,...,10,59.90,0,0.00,0,0.00,0,0.0,Inline,2021-04
1,2021,11,US,KS,MID WEST,MW5,OVERLAND PARK,OTHER BUS.,94 OPTICAL,F FRAMES,...,18,1079.82,8,479.92,4,239.96,0,0.0,Inline,2021-11
2,2022,4,US,MI,MID WEST,MW1,BLOOMFIELD,FRESH FOOD,65 PRODUCE,1 PRODUCE,...,7031,63208.69,3672,33011.28,648,5825.52,0,0.0,Inline,2022-04
3,2021,3,US,HI,LA REGION,LA4,KAPOLEI,SOFTLINES,32 HOUSEWARES,J DINNERWARE,...,284,11357.16,0,0.00,0,0.00,0,0.0,Inline,2021-03
4,2021,12,US,IA,MID WEST,MW4,WEST DES MOINES,SOFTLINES,35 JEWELRY,D COLORED GEMS,...,34,13599.66,16,6399.84,2,799.98,0,0.0,Inline,2021-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,2022,3,US,OH,BUSINESS DELIV-OTHER,DEPOT,DDC ECOM COLUMBUS OH,HARDLINES,24 MAJOR APPLIANCES,H MAJOR APPLIANCES,...,961,28820.39,0,0.00,0,0.00,0,0.0,Online,2022-03
19996,2022,2,US,FL,BUSINESS DELIV-OTHER,DEPOT,DDC ECOM OCALA FL,HARDLINES,24 MAJOR APPLIANCES,H MAJOR APPLIANCES,...,1738,5561582.62,1596,5107184.04,0,0.00,0,0.0,Online,2022-02
19997,2022,8,US,CA,BUSINESS DELIV-OTHER,DEPOT,MDO ECOM W SACRAMENTO CA,HARDLINES,24 MAJOR APPLIANCES,H MAJOR APPLIANCES,...,11,14299.89,0,0.00,0,0.00,0,0.0,Online,2022-08
19998,2021,7,US,GA,BUSINESS DELIV-OTHER,DEPOT,DDC ECOM ATLANTA GA,HARDLINES,27 GARDEN,M PATIO,...,9,20699.91,0,0.00,0,0.00,0,0.0,Online,2021-07
19999,2022,9,US,IL,BUSINESS DELIV-OTHER,DEPOT,MDO ECOM ITASCA IL,HARDLINES,24 MAJOR APPLIANCES,H MAJOR APPLIANCES,...,15,9449.85,0,0.00,0,0.00,0,0.0,Online,2022-09

In [53]:
#Flitering US cntry only

filter1 = data_combine[data_combine['COMPANY_CODE']=='US']

In [107]:
#filter1 = data_combine[data_combine['COMPANY_CODE']=='US']

In [54]:
filter1['BI_RPT_STATE_CODE'].nunique()

48

In [55]:
filter1['BI_RPT_STATE_CODE'].unique()

array(['SC', 'KS', 'MI', 'HI', 'IA', 'FL', 'VA', 'OH', 'AL', 'ND', 'ID',
       'GA', 'NM', 'WA', 'TN', 'NE', 'KY', 'PA', 'SD', 'IL', 'TX', 'NY',
       'UT', 'AZ', 'PR', 'CO', 'MT', 'MN', 'CA', 'DE', 'NH', 'NJ', 'MO',
       'IN', 'OR', 'LA', 'NV', 'OK', 'AK', 'MA', 'MS', 'NC', 'WI', 'MD',
       'DC', 'VT', 'CT', 'AR'], dtype=object)

In [56]:
filter1['BI_RPT_REGION_DESC'].unique()

array(['SOUTHEAST', 'MID WEST', 'LA REGION', 'NORTHEAST', 'NORTHWEST',
       'SD REGION', 'TEXAS REGION', 'BAY AREA', 'BUSINESS CENTERS',
       'BUSINESS DELIV-OTHER'], dtype=object)

In [60]:
#Filtering region

# filter2= filter1["BI_RPT_REGION_DESC"].isin(["SOUTHEAST", "MID WEST", "LA REGION", "NORTHEAST", "NORTHWEST", "SD REGION", "TEXAS REGION",\
#                                    "BAY AREA"])

In [108]:
# filter_region = filter1[filter2]

In [128]:
filter1["BI_RPT_REGION_DESC"].nunique()

10

In [129]:
filter1["BI_RPT_DISTRICT_DESC"].nunique()

37

In [130]:
filter1["BI_RPT_DISTRICT_DESC"].unique() #deport sirf online k lia h

array(['SE4', 'MW5', 'MW1', 'LA4', 'MW4', 'SE2', 'NE3', 'MW3', 'NW3',
       'SE3', 'SD1', 'NW2', 'MW6', 'NE6', 'MW2', 'TE1', 'NW1', 'SD2',
       'SE5', 'SD3', 'NW4', 'BA2', 'NE2', 'NE5', 'NE4', 'TE3', 'NE1',
       'TE2', 'SE1', 'BD1', 'LA2', 'BA3', 'LA3', 'LA1', 'BA1', 'BD2',
       'DEPOT'], dtype=object)

In [131]:
filter1['LOCATION_LONG_NAME'].nunique()      #543 Location

603

In [132]:
filter1.columns

Index(['CALENDAR_YR_NUM', 'CALENDAR_MO_NUM', 'COMPANY_CODE',
       'BI_RPT_STATE_CODE', 'BI_RPT_REGION_DESC', 'BI_RPT_DISTRICT_DESC',
       'LOCATION_LONG_NAME', 'MAJOR_DEPT_GRP_LONG_DESC',
       'BI_DEPARTMENT_NUM_LDESC', 'BI_MAJOR_CATEGORY_CODE_DESC',
       'BI_GROUP_CATEGORY_CODE_DESC', 'BI_ITEM_CATEGORY_CODE_DESC',
       'ITEM_DESC_1', 'OnHand_QTY', 'OnHand_AMT', 'OnOrder_QTY', 'OnOrder_AMT',
       'InTransit_QTY', 'InTransit_AMT', 'Non-Saleable-Items_QTY',
       'Non-Saleable-Items_AMT', 'Data_type', 'year_month'],
      dtype='object')

In [133]:
filter1['MAJOR_DEPT_GRP_LONG_DESC'].unique()

array(['FOOD', 'OTHER BUS.', 'FRESH FOOD', 'SOFTLINES', 'HARDLINES',
       'NOT APPLICABLE MAJOR DEPARTMENT GROUP LONG DESCRIPTION'],
      dtype=object)

In [134]:
#Filtering product items only 

product_item = ['FOOD', 'FRESH FOOD', 'SOFTLINES', 'HARDLINES']

filter_product = filter1[filter1['MAJOR_DEPT_GRP_LONG_DESC'].isin(product_item)]

In [135]:
data_rename = filter_product.rename(columns={'CALENDAR_YR_NUM': 'Year', 'CALENDAR_MO_NUM': 'Month', 'COMPANY_CODE': 'Cntry', \
                             'BI_RPT_STATE_CODE': 'State_Code', "BI_RPT_REGION_DESC": "Region", 'BI_RPT_DISTRICT_DESC': "Dist_Code", \
                             "LOCATION_LONG_NAME": "Location", "MAJOR_DEPT_GRP_LONG_DESC": "Major Department"})

In [136]:
data_rename = data_rename.rename(columns={'BI_DEPARTMENT_NUM_LDESC': 'Department', "BI_MAJOR_CATEGORY_CODE_DESC": "Major_Category", \
                                            "BI_GROUP_CATEGORY_CODE_DESC":  "Grp_ctgry", "BI_ITEM_CATEGORY_CODE_DESC": "Item_ctgry", \
                                            "ITEM_DESC_1": "Item"})

In [137]:
data_rename

,Year,Month,Cntry,State_Code,Region,Dist_Code,Location,Major Department,Department,Major_Category,...,OnHand_QTY,OnHand_AMT,OnOrder_QTY,OnOrder_AMT,InTransit_QTY,InTransit_AMT,Non-Saleable-Items_QTY,Non-Saleable-Items_AMT,Data_type,year_month
0,2021,4,US,SC,SOUTHEAST,SE4,MT PLEASANT,FOOD,13 FOOD,T BREAD,...,10,59.90,0,0.00,0,0.00,0,0.0,Inline,2021-04
2,2022,4,US,MI,MID WEST,MW1,BLOOMFIELD,FRESH FOOD,65 PRODUCE,1 PRODUCE,...,7031,63208.69,3672,33011.28,648,5825.52,0,0.0,Inline,2022-04
3,2021,3,US,HI,LA REGION,LA4,KAPOLEI,SOFTLINES,32 HOUSEWARES,J DINNERWARE,...,284,11357.16,0,0.00,0,0.00,0,0.0,Inline,2021-03
4,2021,12,US,IA,MID WEST,MW4,WEST DES MOINES,SOFTLINES,35 JEWELRY,D COLORED GEMS,...,34,13599.66,16,6399.84,2,799.98,0,0.0,Inline,2021-12
6,2022,6,US,VA,NORTHEAST,NE3,PENTAGON CITY,FOOD,19 DELI,D DIPS SPREADS AND CONDIMENTS,...,13102,117786.98,29400,264306.00,0,0.00,0,0.0,Inline,2022-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,2022,3,US,OH,BUSINESS DELIV-OTHER,DEPOT,DDC ECOM COLUMBUS OH,HARDLINES,24 MAJOR APPLIANCES,H MAJOR APPLIANCES,...,961,28820.39,0,0.00,0,0.00,0,0.0,Online,2022-03
19996,2022,2,US,FL,BUSINESS DELIV-OTHER,DEPOT,DDC ECOM OCALA FL,HARDLINES,24 MAJOR APPLIANCES,H MAJOR APPLIANCES,...,1738,5561582.62,1596,5107184.04,0,0.00,0,0.0,Online,2022-02
19997,2022,8,US,CA,BUSINESS DELIV-OTHER,DEPOT,MDO ECOM W SACRAMENTO CA,HARDLINES,24 MAJOR APPLIANCES,H MAJOR APPLIANCES,...,11,14299.89,0,0.00,0,0.00,0,0.0,Online,2022-08
19998,2021,7,US,GA,BUSINESS DELIV-OTHER,DEPOT,DDC ECOM ATLANTA GA,HARDLINES,27 GARDEN,M PATIO,...,9,20699.91,0,0.00,0,0.00,0,0.0,Online,2021-07
19999,2022,9,US,IL,BUSINESS DELIV-OTHER,DEPOT,MDO ECOM ITASCA IL,HARDLINES,24 MAJOR APPLIANCES,H MAJOR APPLIANCES,...,15,9449.85,0,0.00,0,0.00,0,0.0,Online,2022-09

In [138]:
data_rename.columns

Index(['Year', 'Month', 'Cntry', 'State_Code', 'Region', 'Dist_Code',
       'Location', 'Major Department', 'Department', 'Major_Category',
       'Grp_ctgry', 'Item_ctgry', 'Item', 'OnHand_QTY', 'OnHand_AMT',
       'OnOrder_QTY', 'OnOrder_AMT', 'InTransit_QTY', 'InTransit_AMT',
       'Non-Saleable-Items_QTY', 'Non-Saleable-Items_AMT', 'Data_type',
       'year_month'],
      dtype='object')

In [139]:
data_reindex = data_rename.reindex(columns= ['Year', 'Month', 'year_month', 'Data_type', 'Cntry', 'Region', 'State_Code', \
                               'Dist_Code', 'Location', 'Major Department', 'Department', 'Major_Category', \
                               'Grp_ctgry', 'Item_ctgry', 'Item', 'OnHand_QTY', 'OnHand_AMT', 'OnOrder_QTY', \
                               'OnOrder_AMT', 'InTransit_QTY', 'InTransit_AMT', 'Non-Saleable-Items_QTY', \
                               'Non-Saleable-Items_AMT'])

In [140]:
data_reindex

,Year,Month,year_month,Data_type,Cntry,Region,State_Code,Dist_Code,Location,Major Department,...,Item_ctgry,Item,OnHand_QTY,OnHand_AMT,OnOrder_QTY,OnOrder_AMT,InTransit_QTY,InTransit_AMT,Non-Saleable-Items_QTY,Non-Saleable-Items_AMT
0,2021,4,2021-04,Inline,US,SOUTHEAST,SC,SE4,MT PLEASANT,FOOD,...,TAD SPECIALTY BREAD,IRISH SODA BREAD 2.5 LBS,10,59.90,0,0.00,0,0.00,0,0.0
2,2022,4,2022-04,Inline,US,MID WEST,MI,MW1,BLOOMFIELD,FRESH FOOD,...,1K1 SALAD KITS ORGANIC,ORGANIC CAESAR SALAD KIT,7031,63208.69,3672,33011.28,648,5825.52,0,0.0
3,2021,3,2021-03,Inline,US,LA REGION,HI,LA4,KAPOLEI,SOFTLINES,...,JAB CASUAL 20PC OR LESS SETS,GIBSON MONTEREY 16PC BLUE,284,11357.16,0,0.00,0,0.00,0,0.0
4,2021,12,2021-12,Inline,US,MID WEST,IA,MW4,WEST DES MOINES,SOFTLINES,...,DSB SEMI PREC PENDANTS OR NECKLACE,NJ597-1-98 14KYG RD 10MM,34,13599.66,16,6399.84,2,799.98,0,0.0
6,2022,6,2022-06,Inline,US,NORTHEAST,VA,NE3,PENTAGON CITY,FOOD,...,DDA DIPS,SPINACH ARTICHOKE 31 OZ,13102,117786.98,29400,264306.00,0,0.00,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,2022,3,2022-03,Online,US,BUSINESS DELIV-OTHER,OH,DEPOT,DDC ECOM COLUMBUS OH,HARDLINES,...,HCC ACCESSORIES,"LG 29"" LAUNDRY STACK KIT",961,28820.39,0,0.00,0,0.00,0,0.0
19996,2022,2,2022-02,Online,US,BUSINESS DELIV-OTHER,FL,DEPOT,DDC ECOM OCALA FL,HARDLINES,...,HAE FRENCH 4 DOOR DRAWER,KM ELITE 72795 29.5 CU.FT,1738,5561582.62,1596,5107184.04,0,0.00,0,0.0
19997,2022,8,2022-08,Online,US,BUSINESS DELIV-OTHER,CA,DEPOT,MDO ECOM W SACRAMENTO CA,HARDLINES,...,HBF TOP LOAD GAS SUITES,SS WA50M7450AW DVG50M7450,11,14299.89,0,0.00,0,0.00,0,0.0
19998,2021,7,2021-07,Online,US,BUSINESS DELIV-OTHER,GA,DEPOT,DDC ECOM ATLANTA GA,HARDLINES,...,MBD DINING WICKER,LAGO BRISA 9PC DINING,9,20699.91,0,0.00,0,0.00,0,0.0
19999,2022,9,2022-09,Online,US,BUSINESS DELIV-OTHER,IL,DEPOT,MDO ECOM ITASCA IL,HARDLINES,...,HGA TOP CONTROL DISHWASHER,WP WDT710PAHZ DISHWASER,15,9449.85,0,0.00,0,0.00,0,0.0

In [141]:
data_reindex.isnull().sum()

Year                      0
Month                     0
year_month                0
Data_type                 0
Cntry                     0
Region                    0
State_Code                0
Dist_Code                 0
Location                  0
Major Department          0
Department                0
Major_Category            0
Grp_ctgry                 0
Item_ctgry                0
Item                      0
OnHand_QTY                0
OnHand_AMT                0
OnOrder_QTY               0
OnOrder_AMT               0
InTransit_QTY             0
InTransit_AMT             0
Non-Saleable-Items_QTY    0
Non-Saleable-Items_AMT    0
dtype: int64

In [142]:
## Product Heirarchy 

data_product_drop = data_reindex.drop(['Grp_ctgry', 'Item_ctgry'], axis=1)

In [143]:
data_product_drop

,Year,Month,year_month,Data_type,Cntry,Region,State_Code,Dist_Code,Location,Major Department,...,Major_Category,Item,OnHand_QTY,OnHand_AMT,OnOrder_QTY,OnOrder_AMT,InTransit_QTY,InTransit_AMT,Non-Saleable-Items_QTY,Non-Saleable-Items_AMT
0,2021,4,2021-04,Inline,US,SOUTHEAST,SC,SE4,MT PLEASANT,FOOD,...,T BREAD,IRISH SODA BREAD 2.5 LBS,10,59.90,0,0.00,0,0.00,0,0.0
2,2022,4,2022-04,Inline,US,MID WEST,MI,MW1,BLOOMFIELD,FRESH FOOD,...,1 PRODUCE,ORGANIC CAESAR SALAD KIT,7031,63208.69,3672,33011.28,648,5825.52,0,0.0
3,2021,3,2021-03,Inline,US,LA REGION,HI,LA4,KAPOLEI,SOFTLINES,...,J DINNERWARE,GIBSON MONTEREY 16PC BLUE,284,11357.16,0,0.00,0,0.00,0,0.0
4,2021,12,2021-12,Inline,US,MID WEST,IA,MW4,WEST DES MOINES,SOFTLINES,...,D COLORED GEMS,NJ597-1-98 14KYG RD 10MM,34,13599.66,16,6399.84,2,799.98,0,0.0
6,2022,6,2022-06,Inline,US,NORTHEAST,VA,NE3,PENTAGON CITY,FOOD,...,D DIPS SPREADS AND CONDIMENTS,SPINACH ARTICHOKE 31 OZ,13102,117786.98,29400,264306.00,0,0.00,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,2022,3,2022-03,Online,US,BUSINESS DELIV-OTHER,OH,DEPOT,DDC ECOM COLUMBUS OH,HARDLINES,...,H MAJOR APPLIANCES,"LG 29"" LAUNDRY STACK KIT",961,28820.39,0,0.00,0,0.00,0,0.0
19996,2022,2,2022-02,Online,US,BUSINESS DELIV-OTHER,FL,DEPOT,DDC ECOM OCALA FL,HARDLINES,...,H MAJOR APPLIANCES,KM ELITE 72795 29.5 CU.FT,1738,5561582.62,1596,5107184.04,0,0.00,0,0.0
19997,2022,8,2022-08,Online,US,BUSINESS DELIV-OTHER,CA,DEPOT,MDO ECOM W SACRAMENTO CA,HARDLINES,...,H MAJOR APPLIANCES,SS WA50M7450AW DVG50M7450,11,14299.89,0,0.00,0,0.00,0,0.0
19998,2021,7,2021-07,Online,US,BUSINESS DELIV-OTHER,GA,DEPOT,DDC ECOM ATLANTA GA,HARDLINES,...,M PATIO,LAGO BRISA 9PC DINING,9,20699.91,0,0.00,0,0.00,0,0.0
19999,2022,9,2022-09,Online,US,BUSINESS DELIV-OTHER,IL,DEPOT,MDO ECOM ITASCA IL,HARDLINES,...,H MAJOR APPLIANCES,WP WDT710PAHZ DISHWASER,15,9449.85,0,0.00,0,0.00,0,0.0

In [145]:
#data_product_drop.to_excel('Output\\Inln-Onln_combine.xlsx', index=False)

In [146]:
data_product_drop.shape

(14113, 21)

## Loading Sales Data

In [38]:

data_Sales_Inline = pd.read_excel('C:\\Users\\Ramshankar\\OneDrive - iLink Systems Inc\\Documents\\Costco\\Dataset\\Inventory Visibility - Dataset Updated.xlsx', sheet_name= 'Sales Inline')

In [41]:
len(data_Sales_Inline.columns)

21

In [42]:

data_Sales_Online = pd.read_excel('C:\\Users\\Ramshankar\\OneDrive - iLink Systems Inc\\Documents\\Costco\\Dataset\\Inventory Visibility - Dataset Updated.xlsx', sheet_name= 'Sales Online')

In [43]:
data_Sales_Online

,CALENDAR_YR_NUM,CALENDAR_MO_NUM,COMPANY_CODE,BI_RPT_STATE_CODE,BI_RPT_REGION_DESC,BI_RPT_DISTRICT_DESC,LOCATION_LONG_NAME,MAJOR_DEPT_GRP_LONG_DESC,BI_DEPARTMENT_NUM_LDESC,BI_MAJOR_CATEGORY_CODE_DESC,...,BI_ITEM_CATEGORY_CODE_DESC,ITEM_DESC_1,WK1_SALES,WK2_SALES,WK3_SALES,WK4_SALES,WK1_SALES_AMT,WK2_SALES_AMT,WK3_SALES_AMT,WK4_SALES_AMT
0,2022,11,US,OH,BUSINESS DELIV-OTHER,DEPOT,DDC ECOM COLUMBUS OH,SOFTLINES,38 HOME FURNISHINGS,I MATTRESSES,...,IAG FULL MATTRESS ONLY,SEALY CARVER FULL FIRM,0,25,72,43,0.00,14999.75,43199.28,23999.60
1,2022,10,US,WA,NORTHWEST,DEPOT,AUBURN OPTICAL LAB,OTHER BUS.,94 OPTICAL,F FRAMES,...,FMP FRAME MENS PLASTIC,KS (DS) LUCAS,0,1,0,0,0.00,59.99,0.00,0.00
2,2022,10,US,FL,BUSINESS DELIV-OTHER,DEPOT,DDC ECOM OCALA FL,HARDLINES,27 GARDEN,Q PATIO MISC,...,QAE CANTILEVER UMBRELLA,ATL 10'X13' SQR NONLED,4,0,0,0,3399.96,0.00,0.00,0.00
3,2022,10,US,CA,BUSINESS DELIV-OTHER,DEPOT,MDO ECOM W SACRAMENTO CA,HARDLINES,24 MAJOR APPLIANCES,A TVS,...,AGC 65 IN ENTRY TVS,"HISENSE 65A65H 65""",1,0,0,0,399.99,0.00,0.00,0.00
4,2022,11,US,GA,BUSINESS DELIV-OTHER,DEPOT,DDC ECOM ATLANTA GA,HARDLINES,24 MAJOR APPLIANCES,A TVS,...,AEC 55 IN ENTRY TVS,"LG 55UQ8000AUB 55""",0,23,18,47,0.00,8279.79,6869.82,17389.53
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2022,11,US,TX,BUSINESS DELIV-OTHER,DEPOT,KATY ECOMMERCE,HARDLINES,24 MAJOR APPLIANCES,M COMPUTERS,...,MBB MACBOOKS,"MBA 13"" M1 256GB SG",0,0,1,0,0.00,0.00,949.99,0.00
9996,2022,11,US,TX,BUSINESS DELIV-OTHER,DEPOT,DDC ECOM GARLAND TX,HARDLINES,24 MAJOR APPLIANCES,A TVS,...,AGC 65 IN ENTRY TVS,"SAMSUNG 65TU700D 65""",0,57,106,252,0.00,27439.43,50418.95,115647.48
9997,2022,10,CN,ON,OTHER BUSINESS CN,DEPOT,VAUGHAN ECOMMERCE,HARDLINES,24 MAJOR APPLIANCES,H WHITEGOODS,...,HKA UPRIGHT FREEZER,FRIGIDAIRE FFUM0623AW,60,17,0,0,28909.41,8329.83,0.00,0.00
9998,2022,10,US,CA,BUSINESS DELIV-OTHER,DEPOT,DDC ECOM STOCKTON CA,SOFTLINES,38 HOME FURNISHINGS,J UPHOLSTERY,...,JAK FABRIC SECTIONALS,TISDALE 6PC FAB SEC,27,13,0,0,51999.74,25999.87,0.00,0.00
9999,2022,11,US,CA,BUSINESS DELIV-OTHER,DEPOT,TRACY ECOMMERCE,HARDLINES,24 MAJOR APPLIANCES,B AUDIO,...,BAB IN-EAR HEADPHONES,KLIPSCH KC5 II TRUE,0,0,4,0,0.00,0.00,239.88,0.00