In [1]:
import numpy as np
import pandas as pd

In [2]:
Er_LSTM= pd.read_excel('C:\\Users\\Ramshankar\\OneDrive - iLink Systems Inc\\Documents\\Costco\\Dataset\\Final Output\\Weekly\\Error_Output_all_LSTM_Weekly.xlsx')

In [8]:
Er_LSTM= Er_LSTM.rename(columns= {'MSE_Score': 'MSE_LSTM', 'RMSE_Score': 'RMSE_LSTM'})

In [4]:
Er_prophet = pd.read_excel('C:\\Users\\Ramshankar\\OneDrive - iLink Systems Inc\\Documents\\Costco\\Dataset\\Final Output\\Weekly\\Prophet\\Error_Output_all_Prophet_Weekly.xlsx')

In [9]:
Er_prophet= Er_prophet.rename(columns= {'MSE_Score': 'MSE_prophet', 'RMSE_Score': 'RMSE_prophet'})

In [6]:
Er_Sarima = pd.read_excel('C:\\Users\\Ramshankar\\OneDrive - iLink Systems Inc\\Documents\\Costco\\Dataset\\Final Output\\Weekly\\SARIMA\\Error_Output_all_SARIMA_Weekly.xlsx')

In [11]:
Er_Sarima= Er_Sarima.rename(columns= {'MSE_Score': 'MSE_sarima', 'RMSE_Score': 'RMSE_sarima'})

In [26]:
from functools import reduce

data_frames = [Er_LSTM, Er_prophet, Er_Sarima]

df_merged = reduce(lambda  left,right: pd.merge(left,right,on=['Location', 'Item'],
                                            how='inner'), data_frames)

In [27]:
df_merged

,MSE_LSTM,RMSE_LSTM,Location,Item,MSE_prophet,RMSE_prophet,MSE_sarima,RMSE_sarima
0,8265.146159,90.912849,FREMONT,CHICKEN XXXXX - O,213.104692,14.598106,391.894453,19.796324
1,329941.001681,574.404911,FREMONT,DRUMSTICKS NNNN,8855.972364,94.106176,11231.423750,105.978412
2,2932.063427,54.148531,FREMONT,FILLET QQQQ,33.509600,5.788748,59.182342,7.693006
3,5019.568427,70.848913,HAYWARD,CHICKEN XXXXX - O,761.349528,27.592563,329.022051,18.138965
4,302172.924760,549.702578,HAYWARD,DRUMSTICKS NNNN,16839.408048,129.766745,13497.757828,116.179851
5,4084.015982,63.906306,HAYWARD,FILLET QQQQ,165.144168,12.850843,81.834272,9.046230
6,2380.277349,48.788086,LAKEWOOD,CHICKEN XXXXX - O,267.521915,16.356097,135.438526,11.637806
7,82182.633869,286.675136,LAKEWOOD,DRUMSTICKS NNNN,15533.200677,124.632262,4532.387683,67.323010
8,1766.706881,42.032212,LAKEWOOD,FILLET QQQQ,86.522627,9.301754,50.076129,7.076449
9,8037.921751,89.654458,RICHMOND CA,CHICKEN XXXXX - O,567.749693,23.827499,415.670081,20.387989
10,351413.465363,592.801371,RICHMOND CA,DRUMSTICKS NNNN,17136.144429,130.905097,9978.766280,99.893775
11,6674.938691,81.700298,RICHMOND CA,FILLET QQQQ,760.248779,27.572609,234.245689,15.305087
12,32019.179796,178.939039,S SAN FRANCISCO BUS CTR,BEEF OOOO - GT,3244.383401,56.959489,3099.571570,55.673796
13,28936.732861,170.108004,S SAN FRANCISCO BUS CTR,DRUMSTICKS NNNN,716.266521,26.763156,1591.837665,39.897840

In [28]:
df_merged= df_merged.reindex(columns=['Location', 'Item', 'MSE_LSTM', 'RMSE_LSTM', 'MSE_prophet', 'RMSE_prophet', 'MSE_sarima', 'RMSE_sarima'])

In [29]:
df_merged

,Location,Item,MSE_LSTM,RMSE_LSTM,MSE_prophet,RMSE_prophet,MSE_sarima,RMSE_sarima
0,FREMONT,CHICKEN XXXXX - O,8265.146159,90.912849,213.104692,14.598106,391.894453,19.796324
1,FREMONT,DRUMSTICKS NNNN,329941.001681,574.404911,8855.972364,94.106176,11231.423750,105.978412
2,FREMONT,FILLET QQQQ,2932.063427,54.148531,33.509600,5.788748,59.182342,7.693006
3,HAYWARD,CHICKEN XXXXX - O,5019.568427,70.848913,761.349528,27.592563,329.022051,18.138965
4,HAYWARD,DRUMSTICKS NNNN,302172.924760,549.702578,16839.408048,129.766745,13497.757828,116.179851
5,HAYWARD,FILLET QQQQ,4084.015982,63.906306,165.144168,12.850843,81.834272,9.046230
6,LAKEWOOD,CHICKEN XXXXX - O,2380.277349,48.788086,267.521915,16.356097,135.438526,11.637806
7,LAKEWOOD,DRUMSTICKS NNNN,82182.633869,286.675136,15533.200677,124.632262,4532.387683,67.323010
8,LAKEWOOD,FILLET QQQQ,1766.706881,42.032212,86.522627,9.301754,50.076129,7.076449
9,RICHMOND CA,CHICKEN XXXXX - O,8037.921751,89.654458,567.749693,23.827499,415.670081,20.387989
10,RICHMOND CA,DRUMSTICKS NNNN,351413.465363,592.801371,17136.144429,130.905097,9978.766280,99.893775
11,RICHMOND CA,FILLET QQQQ,6674.938691,81.700298,760.248779,27.572609,234.245689,15.305087
12,S SAN FRANCISCO BUS CTR,BEEF OOOO - GT,32019.179796,178.939039,3244.383401,56.959489,3099.571570,55.673796
13,S SAN FRANCISCO BUS CTR,DRUMSTICKS NNNN,28936.732861,170.108004,716.266521,26.763156,1591.837665,39.897840

In [30]:
df_merged.to_excel('Combine_Error_Output_Weekly_All.xlsx', index=False)